Fix test failures caused by updated js-yaml
Tests were throwing the error:

Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/home/runner/work/opensource.guide/opensource.guide/test/node_modules/js-yaml/index.js:8:11)
    at Object.<anonymous> (/home/runner/work/opensource.guide/opensource.guide/test/prose:59:25)